version: "3.8"

services:
  mysqldb:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_rsgenera
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_rsgenera?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb
volumes:
  db: